# Generated by Django 5.2.4 on 2025-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('general_user', 'General User'), ('client', 'Client'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='general_user', max_length=20),
        ),
    ]
