# Generated by Django 5.2.4 on 2025-11-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user this user is assigned to', limit_choices_to={'role__in': ['admin', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
