# Generated by Django 5.2.4 on 2025-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_assigned_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('general_user', 'General User')], default='general_user', max_length=20),
        ),
    ]
