# Generated by Django 5.2.4 on 2025-07-27 11:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('analysis_name', models.CharField(default='Water Analysis', max_length=100)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('tds', models.DecimalField(decimal_places=2, help_text='Total Dissolved Solids (ppm)', max_digits=6)),
                ('total_alkalinity', models.DecimalField(decimal_places=2, help_text='Total Alkalinity as CaCO₃ (ppm)', max_digits=6)),
                ('hardness', models.DecimalField(decimal_places=2, help_text='Hardness as CaCO₃ (ppm)', max_digits=6)),
                ('chloride', models.DecimalField(decimal_places=2, help_text='Chloride as NaCl (ppm)', max_digits=6)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Hot Side Temperature (°C)', max_digits=4)),
                ('lsi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ls', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lsi_status', models.CharField(blank=True, max_length=20)),
                ('rsi_status', models.CharField(blank=True, max_length=20)),
                ('ls_status', models.CharField(blank=True, max_length=20)),
                ('overall_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Water Analyses',
                'ordering': ['-analysis_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('scaling', 'Scaling Prevention'), ('corrosion', 'Corrosion Prevention'), ('treatment', 'Water Treatment'), ('monitoring', 'Monitoring'), ('maintenance', 'Maintenance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='data_entry.wateranalysis')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trend_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trend_date'],
                'unique_together': {('user', 'parameter', 'trend_date')},
            },
        ),
    ]
