# Generated by Django 5.2.4 on 2025-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_wateranalysis_waterrecommendation_watertrend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wateranalysis',
            name='ls',
        ),
        migrations.RemoveField(
            model_name='wateranalysis',
            name='ls_status',
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='analysis_type',
            field=models.CharField(choices=[('cooling', 'Cooling Water'), ('boiler', 'Boiler Water')], default='cooling', max_length=20),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='basin_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Basin Temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='lr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='lr_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='m_alkalinity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='M-Alkalinity as CaCO₃ (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='psi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='psi_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='sulphate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sulphate (ppm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='chloride',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chloride as NaCl (ppm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='lsi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='lsi_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='overall_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='rsi_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hot Side Temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='wateranalysis',
            name='total_alkalinity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Alkalinity as CaCO₃ (ppm)', max_digits=6, null=True),
        ),
    ]
