# Generated by Django 5.2.4 on 2025-09-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_remove_wateranalysis_ls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooling_ph_min', models.DecimalField(decimal_places=2, default=6.5, max_digits=4)),
                ('cooling_ph_max', models.DecimalField(decimal_places=2, default=7.8, max_digits=4)),
                ('cooling_tds_min', models.DecimalField(decimal_places=2, default=500, max_digits=6)),
                ('cooling_tds_max', models.DecimalField(decimal_places=2, default=800, max_digits=6)),
                ('cooling_hardness_max', models.DecimalField(decimal_places=2, default=300, max_digits=6)),
                ('cooling_alkalinity_max', models.DecimalField(decimal_places=2, default=300, max_digits=6)),
                ('cooling_chloride_max', models.DecimalField(decimal_places=2, default=250, max_digits=6)),
                ('cooling_cycle_min', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('cooling_cycle_max', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('cooling_iron_max', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('boiler_ph_min', models.DecimalField(decimal_places=2, default=10.5, max_digits=4)),
                ('boiler_ph_max', models.DecimalField(decimal_places=2, default=11.5, max_digits=4)),
                ('boiler_tds_min', models.DecimalField(decimal_places=2, default=2500, max_digits=6)),
                ('boiler_tds_max', models.DecimalField(decimal_places=2, default=3500, max_digits=6)),
                ('boiler_hardness_max', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('boiler_alkalinity_min', models.DecimalField(decimal_places=2, default=600, max_digits=6)),
                ('boiler_alkalinity_max', models.DecimalField(decimal_places=2, default=1400, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_analyses', to='data_entry.plant'),
        ),
    ]
