# Generated by Django 5.2.4 on 2025-09-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_plant_wateranalysis_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='description',
        ),
    ]
