# Generated by Django 5.2.4 on 2025-09-01 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_remove_plant_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='accessible_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
