# Generated by Django 5.2.4 on 2025-09-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_plant_accessible_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='accessible_users',
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
