# Generated by Django 5.2.4 on 2025-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_remove_plant_accessible_users_plant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cooling_chloride_enabled',
            field=models.BooleanField(default=False, help_text='Enable chloride monitoring for this plant'),
        ),
    ]
