# Generated by Django 5.2.4 on 2025-09-10 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_plant_cooling_chloride_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watertrend',
            options={'ordering': ['-trend_date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='watertrend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watertrend',
            name='analysis_id',
            field=models.IntegerField(blank=True, help_text='Reference to WaterAnalysis ID', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watertrend',
            unique_together={('user', 'parameter', 'analysis_id')},
        ),
    ]
