# Generated by Django 5.2.4 on 2025-09-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_alter_watertrend_options_and_more'),
        ('data_entry', '0009_alter_watertrend_options_and_more'),
    ]

    operations = [
    ]
