# Generated by Django 5.2.4 on 2025-09-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_merge_20250910_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='boiler_chlorides_enabled',
            field=models.BooleanField(default=False, help_text='Enable chlorides monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_chlorides_max',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_iron_enabled',
            field=models.BooleanField(default=False, help_text='Enable iron monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_iron_max',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_oh_alkalinity_enabled',
            field=models.BooleanField(default=False, help_text='Enable OH-alkalinity monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_oh_alkalinity_max',
            field=models.DecimalField(decimal_places=2, default=900, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_oh_alkalinity_min',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_p_alkalinity_enabled',
            field=models.BooleanField(default=False, help_text='Enable P-alkalinity monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_p_alkalinity_max',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_p_alkalinity_min',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_sulfite_enabled',
            field=models.BooleanField(default=False, help_text='Enable sulfite monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_sulfite_max',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_sulfite_min',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_cycle_enabled',
            field=models.BooleanField(default=False, help_text='Enable cycle of concentration monitoring for this plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_iron_enabled',
            field=models.BooleanField(default=False, help_text='Enable iron monitoring for this plant'),
        ),
    ]
