# Generated by Django 5.2.6 on 2025-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0011_add_optional_water_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='boiler_lsi_enabled',
            field=models.BooleanField(default=False, help_text='Enable LSI monitoring for boiler water'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_lsi_max',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_lsi_min',
            field=models.DecimalField(decimal_places=1, default=-2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_rsi_enabled',
            field=models.BooleanField(default=False, help_text='Enable RSI monitoring for boiler water'),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_rsi_max',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='boiler_rsi_min',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_lsi_enabled',
            field=models.BooleanField(default=False, help_text='Enable LSI monitoring for cooling water'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_lsi_max',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_lsi_min',
            field=models.DecimalField(decimal_places=1, default=-2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_rsi_enabled',
            field=models.BooleanField(default=False, help_text='Enable RSI monitoring for cooling water'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_rsi_max',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='plant',
            name='cooling_rsi_min',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=4),
        ),
    ]
