# Generated by Django 5.2.4 on 2025-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0013_rename_fields_and_add_new_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateranalysis',
            name='boiler_phosphate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Phosphate (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='cycle',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cycle of Concentration', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='do',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Dissolved Oxygen (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Iron (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='oh_alkalinity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OH-Alkalinity as CaCO₃ (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='p_alkalinity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='P-Alkalinity as CaCO₃ (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='phosphate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Phosphate (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='sodium_chloride',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sodium Chloride (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='sulphite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sulphite (ppm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='boiler_do_max',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plant',
            name='boiler_do_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plant',
            name='boiler_sodium_chloride_enabled',
            field=models.BooleanField(default=False, help_text='Enable sodium chloride monitoring for this plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='boiler_sulphite_enabled',
            field=models.BooleanField(default=False, help_text='Enable sulphite monitoring for this plant'),
        ),
    ]
