# Generated by Django 5.2.4 on 2025-11-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_wateranalysis_boiler_phosphate_wateranalysis_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='boiler_lsi_enabled',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='boiler_lsi_max',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='boiler_lsi_min',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='boiler_rsi_enabled',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='boiler_rsi_max',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='boiler_rsi_min',
        ),
    ]
