# Generated by Django 5.2.4 on 2025-11-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0015_remove_boiler_lsi_rsi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this plant', related_name='owned_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_plants_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
