# Generated by Django 5.2.4 on 2025-12-14 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0017_make_plant_parameters_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the water system (e.g., 'Cooling Tower 1', 'Boiler System A')", max_length=100)),
                ('system_type', models.CharField(choices=[('cooling', 'Cooling Water'), ('boiler', 'Boiler Water')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooling_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cooling_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cooling_tds_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_tds_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_hardness_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_alkalinity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_chloride_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_chloride_enabled', models.BooleanField(default=False, help_text='Enable chloride monitoring')),
                ('cooling_cycle_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_cycle_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_cycle_enabled', models.BooleanField(default=False, help_text='Enable cycle of concentration monitoring')),
                ('cooling_iron_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_iron_enabled', models.BooleanField(default=False, help_text='Enable iron monitoring')),
                ('cooling_phosphate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_phosphate_enabled', models.BooleanField(default=False, help_text='Enable phosphate monitoring')),
                ('cooling_lsi_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_lsi_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_lsi_enabled', models.BooleanField(default=False, help_text='Enable LSI monitoring')),
                ('cooling_rsi_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_rsi_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cooling_rsi_enabled', models.BooleanField(default=False, help_text='Enable RSI monitoring')),
                ('boiler_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('boiler_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('boiler_tds_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_tds_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_hardness_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('boiler_alkalinity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_alkalinity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_p_alkalinity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_p_alkalinity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_p_alkalinity_enabled', models.BooleanField(default=False, help_text='Enable P-alkalinity monitoring')),
                ('boiler_oh_alkalinity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_oh_alkalinity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_oh_alkalinity_enabled', models.BooleanField(default=False, help_text='Enable OH-alkalinity monitoring')),
                ('boiler_sulphite_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_sulphite_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_sulphite_enabled', models.BooleanField(default=False, help_text='Enable sulphite monitoring')),
                ('boiler_sodium_chloride_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_sodium_chloride_enabled', models.BooleanField(default=False, help_text='Enable sodium chloride monitoring')),
                ('boiler_do_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_do_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_do_enabled', models.BooleanField(default=False, help_text='Enable dissolved oxygen monitoring')),
                ('boiler_phosphate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_phosphate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boiler_phosphate_enabled', models.BooleanField(default=False, help_text='Enable phosphate monitoring')),
                ('boiler_iron_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('boiler_iron_enabled', models.BooleanField(default=False, help_text='Enable iron monitoring')),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Users assigned to this water system', related_name='assigned_water_systems', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_systems', to='data_entry.plant')),
            ],
            options={
                'ordering': ['plant', 'system_type', 'name'],
                'unique_together': {('plant', 'name', 'system_type')},
            },
        ),
        migrations.AddField(
            model_name='wateranalysis',
            name='water_system',
            field=models.ForeignKey(blank=True, help_text='The specific water system (cooling/boiler) for this analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_analyses', to='data_entry.watersystem'),
        ),
    ]
