# Generated by Django 5.2.4 on 2025-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0018_watersystem_wateranalysis_water_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystem',
            name='cooling_hot_temperature_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hot Side Temperature maximum (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='cooling_hot_temperature_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hot Side Temperature minimum (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='cooling_temperature_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Basin Temperature maximum (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='cooling_temperature_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Basin Temperature minimum (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='cooling_total_alkalinity_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Alkalinity maximum (ppm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='cooling_total_alkalinity_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Alkalinity minimum (ppm)', max_digits=6, null=True),
        ),
    ]
